### ISSUE TITLE
gpu errors

### ISSUE THREAD

**Issue by Chengyuelan** [Na-Z/attMPTI#14] opened 2021-12-09 11:37 UTC
I encountered a GPU problem during the training process on S3DIS dataset . How can I solve it? Thanks for your replying.
usage: main.py [-h]
               [--phase {pretrain,finetune,prototrain,protoeval,mptitrain,mptieval}]
               [--dataset DATASET] [--cvfold CVFOLD] [--data_path DATA_PATH]
               [--pretrain_checkpoint_path PRETRAIN_CHECKPOINT_PATH]
               [--model_checkpoint_path MODEL_CHECKPOINT_PATH]
               [--save_path SAVE_PATH] [--eval_interval EVAL_INTERVAL]
               [--batch_size BATCH_SIZE] [--n_workers N_WORKERS]
               [--n_iters N_ITERS] [--lr LR] [--step_size STEP_SIZE]
               [--gamma GAMMA] [--pretrain_lr PRETRAIN_LR]
               [--pretrain_weight_decay PRETRAIN_WEIGHT_DECAY]
               [--pretrain_step_size PRETRAIN_STEP_SIZE]
               [--pretrain_gamma PRETRAIN_GAMMA] [--n_way N_WAY]
               [--k_shot K_SHOT] [--n_queries N_QUERIES]
               [--n_episode_test N_EPISODE_TEST] [--pc_npts PC_NPTS]
               [--pc_attribs PC_ATTRIBS] [--pc_augm]
               [--pc_augm_scale PC_AUGM_SCALE] [--pc_augm_rot PC_AUGM_ROT]
               [--pc_augm_mirror_prob PC_AUGM_MIRROR_PROB]
               [--pc_augm_jitter PC_AUGM_JITTER] [--dgcnn_k DGCNN_K]
               [--edgeconv_widths EDGECONV_WIDTHS]
               [--dgcnn_mlp_widths DGCNN_MLP_WIDTHS]
               [--base_widths BASE_WIDTHS] [--output_dim OUTPUT_DIM]
               [--use_attention] [--dist_method DIST_METHOD]
               [--n_subprototypes N_SUBPROTOTYPES] [--k_connect K_CONNECT]
               [--sigma SIGMA]
main.py: error: unrecognized arguments: --gpu_id 0 --similarity_function gaussian --output_widths [64]

**Comment by siddharthKatageri** [comment] 2021-12-10 13:05
+1

**Comment by siddharthKatageri** [comment] 2021-12-10 14:38
Hi @Chengyuelan,
remove the following arguments their parameters from train_attMPTI.sh:
--gpu_id 
--similarity_function
--output_widths
They are not present in the argument list of the main.py script.
Doing this works for me.

**Comment by Na-Z** [comment] 2021-12-12 06:07
Sorry, I forgot to update the names of arguments in the script files when cleaning up the code. The problem is fixed with the latest version.

**Closed as completed by Na-Z** 2021-12-12 06:07 UTC

**Comment by Chengyuelan** [comment] 2021-12-12 07:19
Thanks for you replying!But a new problem about cudaErrorIllegalAddress: an illegal memory access was encountered has emerged.
==[Train] Iter: 72 | Loss: 1.0015 |  Accuracy: 0.626465  ==
==[Train] Iter: 73 | Loss: 0.9619 |  Accuracy: 0.765625  ==
==[Train] Iter: 74 | Loss: 1.0150 |  Accuracy: 0.588379  ==
==[Train] Iter: 75 | Loss: 0.9746 |  Accuracy: 0.840088  ==
==[Train] Iter: 76 | Loss: 0.8070 |  Accuracy: 0.834473  ==
==[Train] Iter: 77 | Loss: 0.7784 |  Accuracy: 0.936768  ==
==[Train] Iter: 78 | Loss: 1.1417 |  Accuracy: 0.409424  ==
==[Train] Iter: 79 | Loss: 0.9302 |  Accuracy: 0.484863  ==
==[Train] Iter: 80 | Loss: 0.9774 |  Accuracy: 0.465820  ==
==[Train] Iter: 81 | Loss: 1.0445 |  Accuracy: 0.923828  ==
==[Train] Iter: 82 | Loss: 1.0731 |  Accuracy: 0.464355  ==
==[Train] Iter: 83 | Loss: 1.0980 |  Accuracy: 0.324707  ==
==[Train] Iter: 84 | Loss: 0.9706 |  Accuracy: 0.715820  ==
==[Train] Iter: 85 | Loss: 1.0634 |  Accuracy: 0.364014  ==
==[Train] Iter: 86 | Loss: 0.7598 |  Accuracy: 0.822510  ==
==[Train] Iter: 87 | Loss: 0.9525 |  Accuracy: 0.802246  ==
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    train(args)
  File "/home/attMPTI-main/runs/mpti_train.py", line 59, in train
    loss, accuracy = MPTI.train(data)
  File "/home/attMPTI-main/models/mpti_learner.py", line 63, in train
    query_logits, loss= self.model(support_x, support_y, query_x, query_y)
  File "/home/anaconda3/envs/attMPTI/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/attMPTI-main/models/mpti.py", line 86, in forward
    fg_prototypes, fg_labels = self.getForegroundPrototypes(support_feat, fg_mask, k=self.n_subprototypes)
  File "/home/attMPTI-main/models/mpti.py", line 186, in getForegroundPrototypes
    class_prototypes = self.getMutiplePrototypes(feat, k)
  File "/home/attMPTI-main/models/mpti.py", line 147, in getMutiplePrototypes
    fps_index = fps(feat, None, ratio=ratio, random_start=False).unique()
  File "/home/anaconda3/envs/attMPTI/lib/python3.6/site-packages/torch/tensor.py", line 384, in unique
    return torch.unique(self, sorted=sorted, return_inverse=return_inverse, return_counts=return_counts, dim=dim)
  File "/home/excellence/anaconda3/envs/attMPTI/lib/python3.6/site-packages/torch/functional.py", line 471, in unique
    return_counts=return_counts,
RuntimeError: transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

**Comment by Chengyuelan** [comment] 2021-12-12 07:21
@siddharthKatageri 

Thanks for you replying!But a new problem about cudaErrorIllegalAddress: an illegal memory access was encountered has emerged.
==[Train] Iter: 72 | Loss: 1.0015 | Accuracy: 0.626465 ==
==[Train] Iter: 73 | Loss: 0.9619 | Accuracy: 0.765625 ==
==[Train] Iter: 74 | Loss: 1.0150 | Accuracy: 0.588379 ==
==[Train] Iter: 75 | Loss: 0.9746 | Accuracy: 0.840088 ==
==[Train] Iter: 76 | Loss: 0.8070 | Accuracy: 0.834473 ==
==[Train] Iter: 77 | Loss: 0.7784 | Accuracy: 0.936768 ==
==[Train] Iter: 78 | Loss: 1.1417 | Accuracy: 0.409424 ==
==[Train] Iter: 79 | Loss: 0.9302 | Accuracy: 0.484863 ==
==[Train] Iter: 80 | Loss: 0.9774 | Accuracy: 0.465820 ==
==[Train] Iter: 81 | Loss: 1.0445 | Accuracy: 0.923828 ==
==[Train] Iter: 82 | Loss: 1.0731 | Accuracy: 0.464355 ==
==[Train] Iter: 83 | Loss: 1.0980 | Accuracy: 0.324707 ==
==[Train] Iter: 84 | Loss: 0.9706 | Accuracy: 0.715820 ==
==[Train] Iter: 85 | Loss: 1.0634 | Accuracy: 0.364014 ==
==[Train] Iter: 86 | Loss: 0.7598 | Accuracy: 0.822510 ==
==[Train] Iter: 87 | Loss: 0.9525 | Accuracy: 0.802246 ==
Traceback (most recent call last):
File "main.py", line 101, in
train(args)
File "/home/attMPTI-main/runs/mpti_train.py", line 59, in train
loss, accuracy = MPTI.train(data)
File "/home/attMPTI-main/models/mpti_learner.py", line 63, in train
query_logits, loss= self.model(support_x, support_y, query_x, query_y)
File "/home/anaconda3/envs/attMPTI/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in call
result = self.forward(*input, **kwargs)
File "/home/attMPTI-main/models/mpti.py", line 86, in forward
fg_prototypes, fg_labels = self.getForegroundPrototypes(support_feat, fg_mask, k=self.n_subprototypes)
File "/home/attMPTI-main/models/mpti.py", line 186, in getForegroundPrototypes
class_prototypes = self.getMutiplePrototypes(feat, k)
File "/home/attMPTI-main/models/mpti.py", line 147, in getMutiplePrototypes
fps_index = fps(feat, None, ratio=ratio, random_start=False).unique()
File "/home/anaconda3/envs/attMPTI/lib/python3.6/site-packages/torch/tensor.py", line 384, in unique
return torch.unique(self, sorted=sorted, return_inverse=return_inverse, return_counts=return_counts, dim=dim)
File "/home/excellence/anaconda3/envs/attMPTI/lib/python3.6/site-packages/torch/functional.py", line 471, in unique
return_counts=return_counts,
RuntimeError: transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

**Comment by siddharthKatageri** [comment] 2021-12-13 09:24
@Chengyuelan 
The reason is not very clear. You can check this github issue page: https://github.com/pytorch/pytorch/issues/21819
People solved it by reducing the batch size or by installing a different cuda version.

**Comment by Chengyuelan** [comment] 2021-12-13 12:19
> @Chengyuelan The reason is not very clear. You can check this github issue page: [pytorch/pytorch#21819](https://github.com/pytorch/pytorch/issues/21819) People solved it by reducing the batch size or by installing a different cuda version.

@siddharthKatageri 
Okay thank you. Then when you are training the 'train_attMPTI.sh' file, which version are the pytorch and cuda version of your configuration environment?

**Comment by siddharthKatageri** [comment] 2021-12-14 00:10
@Chengyuelan, so I am using `python 3.8`, `pytorch 1.8.0`, `CUDA 10.2` and `cudnn7.6.5-cuda-10.2`.
